# config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'images'
public_folder: '/images'
collections:
- name: 'pages'
  label: 'Pages'
  create: true
  editor:
    preview: false
  files:
    - label: 'Home page'
      name: 'home'
      file: '_data/home.yml'
      fields:
        - label: 'Banner'
          name: 'banner'
          widget: 'object'
          fields:
            - label: 'Title'
              name: 'title'
              widget: 'string'
            - label: 'Text'
              name: 'text'
              widget: 'string'
            - label: 'Button text'
              name: 'button-text'
              widget: 'string'
            - label: 'Link destination'
              name: 'button-url'
              widget: 'string'
        - label: 'Intro section'
          name: 'intro'
          widget: 'object'
          fields:
            - label: 'Title'
              name: 'title'
              widget: 'string'
            - label: 'Text'
              name: 'text'
              widget: 'markdown'
            - label: 'Image'
              name: 'image'
              widget: 'image'
    - label: 'Beavers'
      name: 'beavers'
      file: '_data/sections/beavers.yml'
      fields:
        - label: 'Heading'
          name: 'title'
          required: false
          widget: 'string' 
        - label: 'Intro'
          name: 'body'
          widget: 'markdown' 
        - label: 'Intro section image'
          name: 'intro-image'
          widget: 'image'
          required: false
        - label: 'Secondary section heading'
          name: 'second-heading'
          required: false
        - label: 'Secondary section text'
          name: 'second-section'
          required: false
          widget: 'markdown'
        - label: 'secondary image'
          name: 'second-image'
          widget: 'image'
          required: false 
        - label: 'Feature 1 heading'
          name: 'box1-heading'
        - label: 'Feature 1 text'
          name: 'box1-text'
          widget: 'markdown'
        - label: 'Feature 1 image'
          name: 'box1-image'
          widget: 'image'
        - label: 'Feature 2 heading'
          name: 'box2-heading'
        - label: 'Feature 2 text'
          name: 'box2-text'
          widget: 'markdown'
        - label: 'Feature 2 image'
          name: 'box2-image'
          widget: 'image'
    - label: 'Cubs'
      name: 'cubs'
      file: '_data/sections/cubs.yml'
      fields:
        - label: 'Heading'
          name: 'title'
          required: false
          widget: 'string' 
        - label: 'Intro'
          name: 'body'
          widget: 'markdown' 
        - label: 'Intro section image'
          name: 'intro-image'
          widget: 'image'
          required: false
        - label: 'Secondary section heading'
          name: 'second-heading'
          required: false
        - label: 'Secondary section text'
          name: 'second-section'
          required: false
          widget: 'markdown'
        - label: 'secondary image'
          name: 'second-image'
          widget: 'image'
          required: false 
        - label: 'Feature 1 heading'
          name: 'box1-heading'
        - label: 'Feature 1 text'
          name: 'box1-text'
          widget: 'markdown'
        - label: 'Feature 1 image'
          name: 'box1-image'
          widget: 'image'
        - label: 'Feature 2 heading'
          name: 'box2-heading'
        - label: 'Feature 2 text'
          name: 'box2-text'
          widget: 'markdown'
        - label: 'Feature 2 image'
          name: 'box2-image'
          widget: 'image'
    - label: 'Scouts'
      name: 'Scouts'
      file: '_data/sections/scouts.yml'
      fields:
        - label: 'Heading'
          name: 'title'
          required: false
          widget: 'string' 
        - label: 'Intro'
          name: 'body'
          widget: 'markdown' 
        - label: 'Intro section image'
          name: 'intro-image'
          widget: 'image'
          required: false
        - label: 'Secondary section heading'
          name: 'second-heading'
          required: false
        - label: 'Secondary section text'
          name: 'second-section'
          required: false
          widget: 'markdown'
        - label: 'secondary image'
          name: 'second-image'
          widget: 'image'
          required: false 
        - label: 'Feature 1 heading'
          name: 'box1-heading'
        - label: 'Feature 1 text'
          name: 'box1-text'
          widget: 'markdown'
        - label: 'Feature 1 image'
          name: 'box1-image'
          widget: 'image'
        - label: 'Feature 2 heading'
          name: 'box2-heading'
        - label: 'Feature 2 text'
          name: 'box2-text'
          widget: 'markdown'
        - label: 'Feature 2 image'
          name: 'box2-image'
          widget: 'image'
    - label: 'Explorers'
      name: 'explorers'
      file: '_data/sections/explorers.yml'
      fields:
        - label: 'Heading'
          name: 'title'
          required: false
          widget: 'string' 
        - label: 'Intro'
          name: 'body'
          widget: 'markdown' 
        - label: 'Intro section image'
          name: 'intro-image'
          widget: 'image'
          required: false
        - label: 'Secondary section heading'
          name: 'second-heading'
          required: false
        - label: 'Secondary section text'
          name: 'second-section'
          required: false
          widget: 'markdown'
        - label: 'secondary image'
          name: 'second-image'
          widget: 'image'
          required: false 
        - label: 'Feature 1 heading'
          name: 'box1-heading'
        - label: 'Feature 1 text'
          name: 'box1-text'
          widget: 'markdown'
        - label: 'Feature 1 image'
          name: 'box1-image'
          widget: 'image'
        - label: 'Feature 2 heading'
          name: 'box2-heading'
        - label: 'Feature 2 text'
          name: 'box2-text'
          widget: 'markdown'
        - label: 'Feature 2 image'
          name: 'box2-image'
          widget: 'image'
    - label: 'Join'
      name: 'join'
      file: 'join.md'
      fields:
        - { label: 'Title', name: 'title', widget: 'hidden' }
        - { label: 'Layout', name: 'layout', widget: 'hidden' }
        - { label: 'Intro', name: 'body', widget: 'markdown' }
        - { label: 'Secondary content', name: 'second-section', widget: 'markdown' }
    - label: 'Contact us'
      name: 'contact'
      file: 'contact.md'
      fields:
        - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
        - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
        - { label: 'Body', name: 'body', widget: 'markdown' }
    - label: 'Location'
      name: 'location'
      file: 'location.md'
      fields:
        - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
        - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
        - { label: 'Body', name: 'body', widget: 'markdown' }
    - label: 'Privacy Notice'
      name: 'privacy'
      file: 'privacy.md'
      fields:
        - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
        - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
        - { label: 'Body', name: 'body', widget: 'markdown' }
- name: 'homepage-features'
  label: 'Homepage features'
  folder: '_homepage-features/'
  create: true
  editor:
    preview: false
  fields:  
        - { label: 'Feature position', name: 'name', widget: 'string' }
        - { label: 'Title', name: 'title', widget: 'string' }
        - { label: 'Body', name: 'body', widget: 'markdown' } 
        - { label: 'Image', name: 'image', widget: 'image' }
